## Lesson 5 Solution

1)	Create an array containing 4 string elements: your first name, your last name, your birth state and your favorite color. 

In [1]:
import numpy as np
from datascience import *

In [7]:
my_odds=np.arange(1,4256,4)
my_odds

array([   1,    5,    9, ..., 4245, 4249, 4253])

In [10]:
np.cumprod(my_odds,dtype=object)

array([1, 5, 45, ...,
       98714570405075852751231650309089159652234517543262971834485134982353875370761058807725006813887881100466611655411453950819055623412542738925482509561154683025761352159172813674374331900725451195123451694275035322507060436259232241344762508853791090784191714615656213697372115065337906617230903680765177934255397484837311259448498351270023878255438112577482475356364966237555896142257173210816771474281795596115622940807375684002277129011988059233112103886470578602983704299097118866650665361434588529125890640615333047401537794331065352339698754631782065930474742536569586802814825091595491672653390966605410130966986008385067761031439612404432576489910659573680438626617701463398347096550489392580673608135081725690136249964728979103833379730419147045535022901278088646697826813624487364874346918297217227623762842113725368309187784394517916447128086158013312362588228663384308848402607173831968825182047648380665477747923721974418748108954042205076921366574201217346373

In [2]:
my_array=make_array("Ken","Horton","TX","Red")
print(my_array)

['Ken' 'Horton' 'TX' 'Red']


a.	Use a numpy function to make all elements uppercase. 

In [3]:
print(np.char.upper(my_array))

['KEN' 'HORTON' 'TX' 'RED']


b.	Use a numpy function to count the number of times the letter “a” appears in each element of your array.

In [5]:
print(np.char.count(my_array,"a"))

[0 0 0 0]


c.	Optional: Use a numpy function to find the length of each element in the array. You may need to Google this. 

In [6]:
mylen=np.vectorize(len)
print(mylen(my_array))

[3 6 2 3]


2)	Create an array containing EVERY OTHER odd number starting with 1 and ending with (and including) 45. 

In [15]:
my_range=np.arange(1,42,4)
print(my_range)
my_range = my_range.astype(float)
print(my_range)

[ 1  5  9 13 17 21 25 29 33 37 41]
[ 1.  5.  9. 13. 17. 21. 25. 29. 33. 37. 41.]


a.	Use numpy to find the sum and the product of the elements of this array.

In [16]:
print(np.sum(my_range))
print(np.prod(my_range))

231.0
7579867420125.0


b.	Use numpy to take the natural log of each element.

In [9]:
print(np.log(my_range))

[0.         1.60943791 2.19722458 2.56494936 2.83321334 3.04452244
 3.21887582 3.36729583 3.49650756 3.61091791 3.71357207 3.80666249]


c.	Optional: The numpy function np.diff finds the difference between adjacent elements of an array. Find the SUM of adjacent elements of this array. 

In [10]:
first=my_range[0:len(my_range)-1]
second=my_range[1:len(my_range)]
print(first+second)

[ 6 14 22 30 38 46 54 62 70 78 86]
